import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { BookOpenText, CheckCircle2, FileBarChart, LogOut, Save, Sparkles, Users } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { getAdminData, translateStandardSection, updateGateCheck, updateStandardSection } from "@/lib/ssesba.functions";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";import { Input } from "@/components/ui/input";import { Label } from "@/components/ui/label";import { Textarea } from "@/components/ui/textarea";import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";import { Badge } from "@/components/ui/badge";

const title="لوحة إدارة مَشْتَق (MASHTAQ) · SSEBA";const description="إدارة نصوص المعيار وبوابة الأهلية ونتائج التقييم وملفات المدرّسين.";
export const Route=createFileRoute("/_authenticated/admin")({head:()=>({meta:[{title},{name:"description",content:description},{property:"og:title",content:title},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:AdminPage});

type AdminData=Awaited<ReturnType<typeof getAdminData>>;
function AdminPage(){const load=useServerFn(getAdminData);const saveSection=useServerFn(updateStandardSection);const saveGate=useServerFn(updateGateCheck);const translate=useServerFn(translateStandardSection);const[data,setData]=useState<AdminData|null>(null);const[error,setError]=useState("");const navigate=useNavigate();const queryClient=useQueryClient();async function refresh(){try{setData(await load());setError("");}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل لوحة الإدارة");}}useEffect(()=>{refresh()},[]);async function logout(){await queryClient.cancelQueries();queryClient.clear();await supabase.auth.signOut();await navigate({to:"/auth",replace:true});}return <main className="min-h-screen bg-brand-paper" dir="rtl"><header className="border-b border-brand-gold/30 bg-brand-navy text-primary-foreground"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div><p className="text-xs text-brand-gold-soft">لوحة المدرّسين والإدارة</p><h1 className="font-display-ar text-2xl">مَشْتَق (MASHTAQ) · SSEBA</h1></div><div className="flex gap-2"><Button asChild variant="outline" className="border-brand-gold/50 bg-transparent text-primary-foreground"><Link to="/">المعيار</Link></Button><Button onClick={logout} variant="outline" className="border-brand-gold/50 bg-transparent text-primary-foreground"><LogOut/>خروج</Button></div></div></header><div className="mx-auto max-w-7xl px-5 py-10">{error&&<div className="rounded-md border border-destructive/30 bg-destructive/10 p-5 text-destructive">{error}</div>}{!data&&!error&&<p>جارٍ تحميل البيانات…</p>}{data&&<Tabs defaultValue="content"><TabsList className="mb-7 h-auto flex-wrap"><TabsTrigger value="content"><BookOpenText/>نصوص المعيار</TabsTrigger><TabsTrigger value="gate"><CheckCircle2/>بوابة الأهلية</TabsTrigger><TabsTrigger value="results"><FileBarChart/>النتائج</TabsTrigger><TabsTrigger value="teachers"><Users/>المدرّسون</TabsTrigger></TabsList><TabsContent value="content" className="space-y-5">{data.sections.map(section=><SectionEditor key={section.id} section={section} onSave={async(payload)=>{await saveSection({data:payload});await refresh()}} onTranslate={async()=>translate({data:{sectionId:section.id,titleAr:section.title_ar,bodyAr:section.body_ar}})}/>)}</TabsContent><TabsContent value="gate" className="space-y-4">{data.checks.map(check=><GateEditor key={check.id} check={check} onSave={async(payload)=>{await saveGate({data:payload});await refresh()}}/>)}</TabsContent><TabsContent value="results"><ResultsTable rows={data.results}/></TabsContent><TabsContent value="teachers"><TeachersTable rows={data.profiles}/></TabsContent></Tabs>}</div></main>}
function SectionEditor({section,onSave,onTranslate}:{section:AdminData["sections"][number];onSave:(x:{sectionId:string;titleAr:string;bodyAr:string;titleEn:string;bodyEn:string;note?:string})=>Promise<void>;onTranslate:()=>Promise<{title:string;body:string}>}){const[arTitle,setArTitle]=useState(section.title_ar);const[arBody,setArBody]=useState(section.body_ar);const[enTitle,setEnTitle]=useState(section.title_en);const[enBody,setEnBody]=useState(section.body_en);const[busy,setBusy]=useState(false);return <section className="rounded-md border bg-card p-6"><h2 className="font-display-ar text-xl text-brand-navy">{section.title_ar}</h2><div className="mt-5 grid gap-5 lg:grid-cols-2"><div><Label>العنوان العربي</Label><Input value={arTitle} onChange={e=>setArTitle(e.target.value)} className="mt-2"/><Label className="mt-4 block">النص العربي المرجعي</Label><Textarea value={arBody} onChange={e=>setArBody(e.target.value)} className="mt-2 min-h-48"/></div><div dir="ltr"><Label>English title</Label><Input value={enTitle} onChange={e=>setEnTitle(e.target.value)} className="mt-2"/><Label className="mt-4 block">English text</Label><Textarea value={enBody} onChange={e=>setEnBody(e.target.value)} className="mt-2 min-h-48"/></div></div><div className="mt-5 flex gap-2"><Button disabled={busy} onClick={async()=>{setBusy(true);await onSave({sectionId:section.id,titleAr:arTitle,bodyAr:arBody,titleEn:enTitle,bodyEn:enBody});setBusy(false)}}><Save/>حفظ ونشر</Button><Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);const r=await onTranslate();setEnTitle(r.title);setEnBody(r.body);setBusy(false)}}><Sparkles/>ترجمة من العربية</Button></div></section>}
function GateEditor({check,onSave}:{check:AdminData["checks"][number];onSave:(x:{id:string;labelAr:string;labelEn:string;guidanceAr?:string;guidanceEn?:string})=>Promise<void>}){const[ar,setAr]=useState(check.label_ar);const[en,setEn]=useState(check.label_en);const[gar,setGar]=useState(check.guidance_ar??"");const[gen,setGen]=useState(check.guidance_en??"");return <section className="rounded-md border bg-card p-5"><div className="grid gap-4 lg:grid-cols-2"><div><Label>الاختبار العربي</Label><Input value={ar} onChange={e=>setAr(e.target.value)} className="mt-2"/><Textarea value={gar} onChange={e=>setGar(e.target.value)} className="mt-2"/></div><div dir="ltr"><Label>English check</Label><Input value={en} onChange={e=>setEn(e.target.value)} className="mt-2"/><Textarea value={gen} onChange={e=>setGen(e.target.value)} className="mt-2"/></div></div><Button className="mt-4" onClick={()=>onSave({id:check.id,labelAr:ar,labelEn:en,guidanceAr:gar,guidanceEn:gen})}><Save/>حفظ</Button></section>}
function ResultsTable({rows}:{rows:AdminData["results"]}){return <div className="overflow-x-auto rounded-md border bg-card"><Table><TableHeader><TableRow><TableHead>المرجع</TableHead><TableHead>القطاع والنشاط</TableHead><TableHead>الأهلية</TableHead><TableHead>الدرجة</TableHead><TableHead>المخاطر</TableHead><TableHead>الحكم</TableHead><TableHead>التاريخ</TableHead></TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.id}><TableCell className="font-mono">{row.reference_code}</TableCell><TableCell>{row.sector_key}<br/><small>{row.activity_name}</small></TableCell><TableCell><Badge variant={row.is_eligible?"default":"destructive"}>{row.is_eligible?"مؤهل":"غير مؤهل"}</Badge></TableCell><TableCell>{row.weighted_score}</TableCell><TableCell>{row.risk_tier}</TableCell><TableCell>{row.verdict}</TableCell><TableCell>{new Date(row.created_at).toLocaleDateString("ar-EG")}</TableCell></TableRow>)}</TableBody></Table></div>}
function TeachersTable({rows}:{rows:AdminData["profiles"]}){return <div className="overflow-x-auto rounded-md border bg-card"><Table><TableHeader><TableRow><TableHead>الاسم</TableHead><TableHead>التخصص</TableHead><TableHead>المسمى</TableHead><TableHead>الجهة</TableHead></TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.id}><TableCell>{row.display_name||"—"}</TableCell><TableCell>{row.specialty||"—"}</TableCell><TableCell>{row.job_title||"—"}</TableCell><TableCell>{row.organization||"—"}</TableCell></TableRow>)}</TableBody></Table></div>}