import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { BookOpenCheck, LogIn, UserPlus } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

const title="دخول المدرّسين | مَشْتَق (MASHTAQ) · SSEBA";
const description="تسجيل دخول وإنشاء ملف المدرّس لإدارة معايير مَشْتَق ونتائج التقييم.";
export const Route=createFileRoute("/auth")({head:()=>({meta:[{title},{name:"description",content:description},{property:"og:title",content:title},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:AuthPage});

function AuthPage(){const navigate=useNavigate();const[signup,setSignup]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const f=new FormData(e.currentTarget);const email=String(f.get("email"));const password=String(f.get("password"));try{if(signup){const{data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin, data:{display_name:String(f.get("displayName")),specialty:String(f.get("specialty")),job_title:String(f.get("jobTitle")),organization:String(f.get("organization")),bio:String(f.get("bio")),preferred_language:"ar"}}});if(error)throw error;if(!data.session){setMessage("تم إنشاء الحساب. راجع بريدك لتأكيده ثم سجّل الدخول.");return;}}else{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;}await navigate({to:"/admin"});}catch(error){setMessage(error instanceof Error?error.message:"تعذر تسجيل الدخول");}finally{setBusy(false);}}
return <main className="min-h-screen bg-brand-paper px-5 py-12" dir="rtl"><div className="mx-auto max-w-lg"><Link to="/" className="mb-8 flex items-center gap-3 text-brand-navy"><span className="grid size-11 place-items-center rounded-md border border-brand-gold font-display-ar text-xl">مـ</span><strong className="font-display-ar text-xl">مَشْتَق (MASHTAQ) · SSEBA</strong></Link><section className="rounded-md border bg-card p-7 shadow-sm"><div className="flex items-center gap-3 text-brand-gold"><BookOpenCheck/><span>بوابة المدرّسين</span></div><h1 className="mt-4 font-display-ar text-3xl font-semibold">{signup?"إنشاء ملف مدرّس":"تسجيل الدخول"}</h1><form onSubmit={submit} className="mt-7 grid gap-4">{signup&&<><Field name="displayName" label="الاسم الظاهر"/><div className="grid gap-4 sm:grid-cols-2"><Field name="specialty" label="التخصص"/><Field name="jobTitle" label="المسمى الوظيفي"/><Field name="organization" label="الجهة"/></div><div><Label htmlFor="bio">نبذة مهنية</Label><Textarea id="bio" name="bio" className="mt-2" maxLength={1000}/></div></>}<Field name="email" label="البريد الإلكتروني" type="email"/><Field name="password" label="كلمة المرور" type="password"/><Button disabled={busy} size="lg" className="bg-brand-navy text-primary-foreground">{signup?<UserPlus/>:<LogIn/>}{busy?"جارٍ المتابعة…":signup?"إنشاء الحساب":"دخول"}</Button>{message&&<p className="text-sm leading-6 text-muted-foreground">{message}</p>}</form><Button variant="link" className="mt-3 px-0 text-brand-navy" onClick={()=>{setSignup(!signup);setMessage("")}}>{signup?"لديك حساب؟ سجّل الدخول":"مدرّس جديد؟ أنشئ ملفك"}</Button></section></div></main>}
function Field({name,label,type="text"}:{name:string;label:string;type?:string}){return <div><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} required className="mt-2 h-11" minLength={type==="password"?8:undefined}/></div>}