import { useMemo, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { AlertTriangle, Building2, CheckCircle2, Sparkles } from "lucide-react";
import { SiteShell } from "./SiteShell"; import { Button } from "@/components/ui/button"; import { Checkbox } from "@/components/ui/checkbox"; import { Label } from "@/components/ui/label"; import { Slider } from "@/components/ui/slider"; import { Textarea } from "@/components/ui/textarea"; import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select"; import { Tabs,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { axes, calculateAssessment, copy, type AssessmentMode, type Lang, type RiskTier } from "@/lib/ssesba-data"; import { suggestHospitalAssessment } from "@/lib/ssesba.functions";

const labels={ar:{title:"تقييم مستشفى نموذجي",eyebrow:"تطبيق واقعي تفاعلي",desc:"مستشفى عام يقدم خدمات علاجية وتشخيصية وصيدلية. راجع بوابة الأهلية، ثم عدّل درجات المحاور وفق الأدلة المتاحة.",gate:"بوابة الأهلية",gateText:"لا يتضمن النشاط الأساسي ربا أو ميسرًا أو سلعًا وخدمات محرمة أو غشًا وغررًا جوهريًا.",risk:"مستوى المخاطر الشرعية",riskNote:"يحدده المراجع المختص؛ لا يستنتجه النظام آليًا.",result:"النتيجة المركبة",score:"الدرجة المرجحة",expert:"خبير",self:"ذاتي",ai_review:"اقتراح AI",analyze:"اقتراح الدرجات",evidence:"وصف النشاط والأدلة",full:"امتثال كامل",compliant:"ممتثل",conditional:"ممتثل بشروط",remediation:"يحتاج معالجة",non_compliant:"غير ممتثل",ineligible:"غير مؤهل",approved:"معتمد",approved_conditional:"معتمد بشروط",rejected:"مرفوض"},en:{title:"Sample hospital assessment",eyebrow:"Interactive real-world application",desc:"A general hospital providing clinical, diagnostic, and pharmacy services. Review eligibility, then adjust each axis using available evidence.",gate:"Eligibility gate",gateText:"The core activity does not involve riba, maysir, prohibited goods or services, fraud, or material gharar.",risk:"Shariah risk tier",riskNote:"Selected by a qualified reviewer; the system does not infer it automatically.",result:"Combined result",score:"Weighted score",expert:"Expert",self:"Self",ai_review:"AI suggestion",analyze:"Suggest scores",evidence:"Activity and evidence description",full:"Full compliance",compliant:"Compliant",conditional:"Conditionally compliant",remediation:"Needs remediation",non_compliant:"Non-compliant",ineligible:"Ineligible",approved:"Approved",approved_conditional:"Approved with conditions",rejected:"Rejected"}} as const;
export function AssessmentPage({lang}:{lang:Lang}){const t=labels[lang];const [mode,setMode]=useState<AssessmentMode>("expert");const [eligible,setEligible]=useState(true);const [risk,setRisk]=useState<RiskTier>("S2");const [scores,setScores]=useState<Record<string,number>>(Object.fromEntries(axes.map(a=>[a.id,a.hospital])));const [description,setDescription]=useState(lang==="ar"?"مستشفى عام، إيراداته من الخدمات الطبية والصيدلية المباحة، لديه تمويل تقليدي محدود، ولجنة حوكمة داخلية وتقارير مالية دورية.":"A general hospital earning revenue from permissible clinical and pharmacy services, with limited conventional financing, internal governance, and periodic financial reporting.");const [aiNote,setAiNote]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const suggest=useServerFn(suggestHospitalAssessment);const result=useMemo(()=>calculateAssessment(scores,eligible,risk),[scores,eligible,risk]);
 async function runAI(){setBusy(true);setError("");try{const r=await suggest({data:{description}});setScores(Object.fromEntries(axes.map((a,i)=>[a.id,r.scores[i]??a.hospital])));setAiNote(r.note)}catch(e){setError(e instanceof Error?e.message:"AI request failed") }finally{setBusy(false)}}
 const bandLabel=result.band==="compliant"&&result.score>=95?t.full:t[result.band as keyof typeof t] as string; const verdict=t[result.verdict as keyof typeof t] as string;
 return <SiteShell lang={lang} eyebrow={t.eyebrow} title={t.title}><div className="mx-auto max-w-7xl px-5 py-10"><div className="mb-8 flex flex-col justify-between gap-5 border-b pb-8 md:flex-row md:items-end"><div className="max-w-3xl"><div className="mb-3 flex items-center gap-2 text-brand-gold"><Building2/><span className="font-semibold">{lang==="ar"?"الرعاية الصحية · ISIC 8610":"Healthcare · ISIC 8610"}</span></div><p className="leading-7 text-muted-foreground">{t.desc}</p></div><Tabs value={mode} onValueChange={v=>setMode(v as AssessmentMode)}><TabsList className="h-11"><TabsTrigger value="expert">{t.expert}</TabsTrigger><TabsTrigger value="self">{t.self}</TabsTrigger><TabsTrigger value="ai_review">{t.ai_review}</TabsTrigger></TabsList></Tabs></div>
 <div className="grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><section className="space-y-7"><div className="rounded-md border bg-card p-5"><div className="flex items-start gap-3"><Checkbox id="eligible" checked={eligible} onCheckedChange={v=>setEligible(v===true)} className="mt-1"/><div><Label htmlFor="eligible" className="text-base">{t.gate}</Label><p className="mt-2 text-sm leading-6 text-muted-foreground">{t.gateText}</p></div></div></div>
 {mode==="ai_review"&&<div className="rounded-md border border-brand-gold/40 bg-brand-parchment p-5"><Label>{t.evidence}</Label><Textarea value={description} onChange={e=>setDescription(e.target.value)} className="mt-3 min-h-28 bg-background"/><Button onClick={runAI} disabled={busy} className="mt-3 bg-brand-navy text-primary-foreground"><Sparkles/>{busy?"…":t.analyze}</Button>{aiNote&&<p className="mt-3 text-sm leading-6">{aiNote}</p>}{error&&<p className="mt-3 text-sm text-destructive">{error}</p>}</div>}
  <div className="space-y-4">{axes.map(axis=>{const score=scores[axis.id]??axis.hospital;return <div key={axis.id} className="rounded-md border bg-card p-5"><div className="mb-4 flex items-baseline justify-between"><div><h3 className="font-semibold">{axis[lang]}</h3><p className="text-xs text-muted-foreground">{lang==="ar"?"الوزن":"Weight"} {axis.weight}%</p></div><output className="font-mono text-xl font-bold text-brand-navy">{score}</output></div><Slider value={[score]} max={100} step={1} onValueChange={v=>setScores({...scores,[axis.id]:v[0]??0})}/></div>})}</div></section>
 <aside className="lg:sticky lg:top-5 lg:self-start"><div className="overflow-hidden rounded-md border bg-card shadow-sm"><div className="bg-brand-navy p-6 text-primary-foreground"><p className="text-sm text-brand-gold-soft">{t.result}</p><div className="mt-2 flex items-end justify-between"><strong className="font-serif text-5xl">{result.score}</strong><span className="pb-1 text-sm">/ 100</span></div></div><div className="space-y-5 p-6"><div><p className="text-xs text-muted-foreground">{lang==="ar"?"النطاق":"Band"}</p><p className="mt-1 text-xl font-semibold">{bandLabel}</p></div><div><Label>{t.risk}</Label><Select value={risk} onValueChange={v=>setRisk(v as RiskTier)}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent>{["S1","S2","S3","S4"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><p className="mt-2 text-xs text-muted-foreground">{t.riskNote}</p></div><div className={`rounded-md p-4 ${result.verdict==="rejected"?"bg-destructive/10 text-destructive":"bg-brand-parchment text-brand-navy"}`}>{result.verdict==="rejected"?<AlertTriangle/>:<CheckCircle2/>}<p className="mt-2 text-lg font-bold">{verdict}</p></div><p className="border-t pt-4 text-xs leading-5 text-muted-foreground">{copy[lang].advisory}</p></div></div></aside></div></div></SiteShell>}
