/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EnRouteImport } from './routes/en'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as RequestRouteImport } from './routes/request'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as EnAssessmentRouteImport } from './routes/en.assessment'
import { Route as EnRequestRouteImport } from './routes/en.request'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EnAssessmentRoute = EnAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => EnRoute,
} as any)
const EnRequestRoute = EnRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => EnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/en': typeof EnRouteWithChildren
  '/explorer': typeof ExplorerRoute
  '/request': typeof RequestRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/en/assessment': typeof EnAssessmentRoute
  '/en/request': typeof EnRequestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/en': typeof EnRouteWithChildren
  '/explorer': typeof ExplorerRoute
  '/request': typeof RequestRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/en/assessment': typeof EnAssessmentRoute
  '/en/request': typeof EnRequestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/en': typeof EnRouteWithChildren
  '/explorer': typeof ExplorerRoute
  '/request': typeof RequestRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/en/assessment': typeof EnAssessmentRoute
  '/en/request': typeof EnRequestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/auth'
    | '/en'
    | '/explorer'
    | '/request'
    | '/admin'
    | '/en/assessment'
    | '/en/request'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/auth'
    | '/en'
    | '/explorer'
    | '/request'
    | '/admin'
    | '/en/assessment'
    | '/en/request'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/assessment'
    | '/auth'
    | '/en'
    | '/explorer'
    | '/request'
    | '/_authenticated/admin'
    | '/en/assessment'
    | '/en/request'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRoute
  EnRoute: typeof EnRouteWithChildren
  ExplorerRoute: typeof ExplorerRoute
  RequestRoute: typeof RequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/en/assessment': {
      id: '/en/assessment'
      path: '/assessment'
      fullPath: '/en/assessment'
      preLoaderRoute: typeof EnAssessmentRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/request': {
      id: '/en/request'
      path: '/request'
      fullPath: '/en/request'
      preLoaderRoute: typeof EnRequestRouteImport
      parentRoute: typeof EnRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EnRouteChildren {
  EnAssessmentRoute: typeof EnAssessmentRoute
  EnRequestRoute: typeof EnRequestRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAssessmentRoute: EnAssessmentRoute,
  EnRequestRoute: EnRequestRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRoute,
  EnRoute: EnRouteWithChildren,
  ExplorerRoute: ExplorerRoute,
  RequestRoute: RequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
