/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as EnRouteImport } from './routes/en'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as RequestRouteImport } from './routes/request'
import { Route as SixRouteImport } from './routes/six'
import { Route as EnAssessmentRouteImport } from './routes/en.assessment'
import { Route as EnAssistantRouteImport } from './routes/en.assistant'
import { Route as EnRequestRouteImport } from './routes/en.request'
import { Route as EnSixRouteImport } from './routes/en.six'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const SixRoute = SixRouteImport.update({
  id: '/six',
  path: '/six',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAssessmentRoute = EnAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => EnRoute,
} as any)
const EnAssistantRoute = EnAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => EnRoute,
} as any)
const EnRequestRoute = EnRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => EnRoute,
} as any)
const EnSixRoute = EnSixRouteImport.update({
  id: '/six',
  path: '/six',
  getParentRoute: () => EnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assistant': typeof AssistantRoute
  '/en': typeof EnRouteWithChildren
  '/explorer': typeof ExplorerRoute
  '/request': typeof RequestRoute
  '/six': typeof SixRoute
  '/en/assessment': typeof EnAssessmentRoute
  '/en/assistant': typeof EnAssistantRoute
  '/en/request': typeof EnRequestRoute
  '/en/six': typeof EnSixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assistant': typeof AssistantRoute
  '/en': typeof EnRouteWithChildren
  '/explorer': typeof ExplorerRoute
  '/request': typeof RequestRoute
  '/six': typeof SixRoute
  '/en/assessment': typeof EnAssessmentRoute
  '/en/assistant': typeof EnAssistantRoute
  '/en/request': typeof EnRequestRoute
  '/en/six': typeof EnSixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assistant': typeof AssistantRoute
  '/en': typeof EnRouteWithChildren
  '/explorer': typeof ExplorerRoute
  '/request': typeof RequestRoute
  '/six': typeof SixRoute
  '/en/assessment': typeof EnAssessmentRoute
  '/en/assistant': typeof EnAssistantRoute
  '/en/request': typeof EnRequestRoute
  '/en/six': typeof EnSixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/assistant'
    | '/en'
    | '/explorer'
    | '/request'
    | '/six'
    | '/en/assessment'
    | '/en/assistant'
    | '/en/request'
    | '/en/six'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/assistant'
    | '/en'
    | '/explorer'
    | '/request'
    | '/six'
    | '/en/assessment'
    | '/en/assistant'
    | '/en/request'
    | '/en/six'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/assistant'
    | '/en'
    | '/explorer'
    | '/request'
    | '/six'
    | '/en/assessment'
    | '/en/assistant'
    | '/en/request'
    | '/en/six'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  AssistantRoute: typeof AssistantRoute
  EnRoute: typeof EnRouteWithChildren
  ExplorerRoute: typeof ExplorerRoute
  RequestRoute: typeof RequestRoute
  SixRoute: typeof SixRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/six': {
      id: '/six'
      path: '/six'
      fullPath: '/six'
      preLoaderRoute: typeof SixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/assessment': {
      id: '/en/assessment'
      path: '/assessment'
      fullPath: '/en/assessment'
      preLoaderRoute: typeof EnAssessmentRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/assistant': {
      id: '/en/assistant'
      path: '/assistant'
      fullPath: '/en/assistant'
      preLoaderRoute: typeof EnAssistantRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/request': {
      id: '/en/request'
      path: '/request'
      fullPath: '/en/request'
      preLoaderRoute: typeof EnRequestRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/six': {
      id: '/en/six'
      path: '/six'
      fullPath: '/en/six'
      preLoaderRoute: typeof EnSixRouteImport
      parentRoute: typeof EnRoute
    }
  }
}

interface EnRouteChildren {
  EnAssessmentRoute: typeof EnAssessmentRoute
  EnAssistantRoute: typeof EnAssistantRoute
  EnRequestRoute: typeof EnRequestRoute
  EnSixRoute: typeof EnSixRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAssessmentRoute: EnAssessmentRoute,
  EnAssistantRoute: EnAssistantRoute,
  EnRequestRoute: EnRequestRoute,
  EnSixRoute: EnSixRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  AssistantRoute: AssistantRoute,
  EnRoute: EnRouteWithChildren,
  ExplorerRoute: ExplorerRoute,
  RequestRoute: RequestRoute,
  SixRoute: SixRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
